name: Build EXE

on:
  push:
    branches: [ master ]

jobs:
  Get-Tag:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Get Tag
        id: tag
        run: |
          echo ${{ toJSON(github) }}

